### ISSUE TITLE
scrollTo function is broken since last release - thank you

### ISSUE THREAD

**Issue by developer-lindner** [fisshy/react-scroll#270]
scrollOffset **(in scroller.js)** always gets negative values which wont work with window.scrollTo
see: https://developer.mozilla.org/de/docs/Web/API/Window/scrollTo

Before merging Pull Requests from a russian guy with russian commits (why, just why!!) it should be tested... ;)

**Comment by fisshy** [comment]
Did you solve it? :)

**Comment by developer-lindner** [comment]
Nope, its just broken... previous version worked. now its just fucked up.

**Comment by fisshy** [comment]
All test passes and I cant reproduce it.

How can I reproduce it? 

Are you using 1.6.1, browser?

**Comment by developer-lindner** [comment]
1.6.1, Chrome Version 61, now 62

**Comment by fisshy** [comment]
Can you add a plunker/code and give me something so I can reproduce it. 

Haven't managed to reproduce it :(

**Comment by developer-lindner** [comment]
Ok, so lets see....

Sometimes **containerElement** is my body tag... using scrollTop here:

`scrollOffset = containerElement.scrollTop + coordinates.top - containerElement.offsetTop;`

ends up in a wrong value...

Using:
`scrollOffset = window.scrollY + coordinates.top - containerElement.offsetTop;`
gives me the right value.

But even if you have the right value, using `containerElement.scrollTop = scrollOffset` wont do anything... instead `window.scrollTo(0, scrollOffset);` would work.

So... it's seriously fucked up for some markups i think. And it's a companies website which i can't share here ;)

**Comment by fisshy** [comment]
All right, I will give it a go and try to solve it :)

**Comment by developer-lindner** [comment]
There are also differences if the parent containers are positioned relative for example.

**Comment by monkseal** [comment]
I'm also having this problem since last version. In the demo app, this part does not work:
```    
        <Link activeClass="scroll-demo-active" to="firstInsideContainer" spy smooth duration={250} containerId="containerElement" style={{ display: "inline-block", margin: "20px" }}>
          Go to first element inside container
          </Link>

          <Link activeClass="scroll-demo-active" to="secondInsideContainer" spy smooth duration={250} containerId="containerElement" style={{ display: "inline-block", margin: "20px" }}>
          Go to second element inside container
          </Link>
          <Element
            name="test7"
            className="scroll-demo-element"
            id="containerElement"
            style={{
              position: "relative",
              height: "200px",
              overflow: "scroll",
              marginBottom: "100px"
            }}
          >
          test 7 (duration and container)

            <Element
              name="firstInsideContainer"
              style={{
                marginBottom: "200px"
              }}
            >
            first element inside container
            </Element>

            <Element
              name="secondInsideContainer"
              style={{
                marginBottom: "200px"
              }}
            >
            second element inside container
            </Element>
          </Element>
```

**Comment by fisshy** [comment]
I'm looking into it, will most likely publish a fix today

**Comment by fisshy** [comment]
Should be fixed in v1.6.2 ( theres a new example in examples as well with using nested containers )

**Comment by podrivo** [comment]
Using `v.1.6.4` and it's still not working.
I think this is related: https://github.com/fisshy/react-scroll/issues/272

**Comment by fisshy** [comment]
Should be fixed, open up if not fixed. Check out https://github.com/fisshy/react-scroll/issues/272
